export type MarketItem = {
  id: string;
  title: string;
  tagline: string;
  type: "dataset" | "model" | "agent" | "tool";
  category: string;
  author: string;
  authorHandle: string;
  price: number; // 0 = free
  rating: number;
  downloads: number;
  updatedAt: string;
  tags: string[];
  description: string;
  gradient: string;
  badge?: string;
  license?: string;
  size?: string;
  github?: string;
};

const gradients = [
  "from-orange-400/70 via-pink-400/60 to-purple-500/60",
  "from-sky-400/70 via-indigo-400/60 to-purple-500/60",
  "from-emerald-400/70 via-teal-400/60 to-cyan-500/60",
  "from-amber-400/70 via-rose-400/60 to-fuchsia-500/60",
  "from-violet-400/70 via-fuchsia-400/60 to-pink-500/60",
  "from-lime-400/70 via-emerald-400/60 to-teal-500/60",
  "from-rose-400/70 via-orange-400/60 to-amber-500/60",
  "from-blue-400/70 via-cyan-400/60 to-teal-500/60",
];

const g = (i: number) => gradients[i % gradients.length];

export const MARKET_ITEMS: MarketItem[] = [
  {
    id: "ds-001",
    title: "GlobalSentiment v3.1",
    tagline: "Multilingual social-media sentiment corpus",
    type: "dataset",
    category: "NLP",
    author: "Aurora Labs",
    authorHandle: "@aurora",
    price: 0,
    rating: 4.8,
    downloads: 12480,
    updatedAt: "2 days ago",
    tags: ["sentiment", "multilingual", "social"],
    description:
      "12M labelled posts across 38 languages with stance and emotion tags. Clean Parquet shards, ready for fine-tuning.",
    gradient: g(0),
    badge: "Trending",
    license: "CC-BY 4.0",
    size: "8.2 GB",
  },
  {
    id: "ds-002",
    title: "UrbanVision-XL",
    tagline: "Street-level imagery with 220 semantic classes",
    type: "dataset",
    category: "Computer Vision",
    author: "Mapline",
    authorHandle: "@mapline",
    price: 49,
    rating: 4.7,
    downloads: 3210,
    updatedAt: "1 week ago",
    tags: ["segmentation", "autonomous", "urban"],
    description:
      "High-resolution urban scenes from 40 cities, fully annotated with pixel-level masks and 3D bounding boxes.",
    gradient: g(1),
    license: "Commercial",
    size: "120 GB",
  },
  {
    id: "ds-003",
    title: "EduQuiz Reasoning",
    tagline: "Step-by-step solutions to 1M K-12 problems",
    type: "dataset",
    category: "Education",
    author: "Lumen EDU",
    authorHandle: "@lumen",
    price: 0,
    rating: 4.6,
    downloads: 8760,
    updatedAt: "5 days ago",
    tags: ["reasoning", "math", "education"],
    description: "Curated K-12 math and science problems with rationales for chain-of-thought training.",
    gradient: g(2),
    license: "MIT",
    size: "2.1 GB",
  },
  {
    id: "md-001",
    title: "Arc-Vision 2B",
    tagline: "Compact vision-language model",
    type: "model",
    category: "Computer Vision",
    author: "ArcML",
    authorHandle: "@arcml",
    price: 129,
    rating: 4.9,
    downloads: 5430,
    updatedAt: "3 days ago",
    tags: ["VLM", "edge", "open-weights"],
    description: "2B parameter VLM with strong document understanding. Quantized GGUF + safetensors included.",
    gradient: g(3),
    badge: "New",
    license: "Apache 2.0",
    size: "4.1 GB",
  },
  {
    id: "md-002",
    title: "Lyra Whisper-Pro",
    tagline: "Speech-to-text optimized for noisy environments",
    type: "model",
    category: "Audio",
    author: "Lyra",
    authorHandle: "@lyra",
    price: 0,
    rating: 4.5,
    downloads: 21340,
    updatedAt: "1 day ago",
    tags: ["ASR", "audio", "realtime"],
    description: "Robust speech recognition fine-tuned on 50k hours of noisy field audio.",
    gradient: g(4),
    license: "Apache 2.0",
    size: "1.6 GB",
  },
  {
    id: "md-003",
    title: "Helios-Code 7B",
    tagline: "Code generation across 30 languages",
    type: "model",
    category: "Code",
    author: "Helios",
    authorHandle: "@helios",
    price: 89,
    rating: 4.7,
    downloads: 6890,
    updatedAt: "1 week ago",
    tags: ["code", "instruct", "open"],
    description: "Instruction-tuned coder built for refactoring, test generation, and migration tasks.",
    gradient: g(5),
    license: "Commercial",
    size: "13 GB",
  },
  {
    id: "ag-001",
    title: "Sage Research Agent",
    tagline: "Autonomous deep-research with citation graph",
    type: "agent",
    category: "Productivity",
    author: "Northbeam",
    authorHandle: "@northbeam",
    price: 24,
    rating: 4.8,
    downloads: 1840,
    updatedAt: "Today",
    tags: ["research", "autonomous", "citations"],
    description: "Multi-step research agent that builds a verifiable citation graph and exports to Notion.",
    gradient: g(6),
    badge: "Featured",
  },
  {
    id: "ag-002",
    title: "Quill Marketing Crew",
    tagline: "Plans, writes and schedules campaigns end-to-end",
    type: "agent",
    category: "Marketing",
    author: "Quill",
    authorHandle: "@quill",
    price: 39,
    rating: 4.6,
    downloads: 940,
    updatedAt: "2 days ago",
    tags: ["marketing", "crew", "social"],
    description: "Five-agent crew: strategist, writer, designer, scheduler, analyst. Connects to your stack.",
    gradient: g(7),
  },
  {
    id: "ag-003",
    title: "Atlas Ops Agent",
    tagline: "Production incident triage and remediation",
    type: "agent",
    category: "DevOps",
    author: "Atlas",
    authorHandle: "@atlas",
    price: 59,
    rating: 4.9,
    downloads: 620,
    updatedAt: "4 days ago",
    tags: ["devops", "incident", "automation"],
    description: "Wires into PagerDuty, GitHub and your runbook to triage and propose fixes.",
    gradient: g(0),
  },
  {
    id: "tl-001",
    title: "Pixel Forge",
    tagline: "Batch image upscale and restoration tool",
    type: "tool",
    category: "AI Image",
    author: "Forge",
    authorHandle: "@forge",
    price: 19,
    rating: 4.7,
    downloads: 4120,
    updatedAt: "3 days ago",
    tags: ["image", "upscale", "restoration"],
    description: "Drop a folder. Get crisp, color-true upscales across 4 model backends.",
    gradient: g(1),
  },
  {
    id: "tl-002",
    title: "FlowCanvas",
    tagline: "Visual workflow builder for AI pipelines",
    type: "tool",
    category: "Workflow",
    author: "FlowCanvas",
    authorHandle: "@flow",
    price: 0,
    rating: 4.4,
    downloads: 9800,
    updatedAt: "1 day ago",
    tags: ["workflow", "low-code", "pipeline"],
    description: "Open-source node editor with 80+ blocks for LLM, vector, audio and vision tasks.",
    gradient: g(2),
    badge: "Popular",
  },
  {
    id: "tl-003",
    title: "Prism Analytics",
    tagline: "Conversational analytics on top of your warehouse",
    type: "tool",
    category: "Analytics",
    author: "Prism",
    authorHandle: "@prism",
    price: 79,
    rating: 4.6,
    downloads: 1530,
    updatedAt: "1 week ago",
    tags: ["analytics", "BI", "SQL"],
    description: "Ask in plain English, get audited SQL, charts, and an exec summary.",
    gradient: g(3),
  },
];

export const CATEGORIES = [
  { slug: "datasets", label: "Datasets", type: "dataset" as const, blurb: "Curated, license-clear data for training and evaluation." },
  { slug: "models", label: "AI / ML Models", type: "model" as const, blurb: "Open and commercial weights with deployment recipes." },
  { slug: "agents", label: "Agents", type: "agent" as const, blurb: "Autonomous and crew-style agents for any domain." },
  { slug: "tools", label: "AI Tools", type: "tool" as const, blurb: "Productivity, workflow, vision, marketing and more." },
];

export const TAG_FILTERS = [
  "All",
  "Free",
  "Paid",
  "NLP",
  "Computer Vision",
  "Audio",
  "Code",
  "Productivity",
  "Marketing",
  "Workflow",
  "Analytics",
  "Education",
  "DevOps",
  "AI Image",
];

export const getItemsByType = (t: MarketItem["type"]) =>
  MARKET_ITEMS.filter((i) => i.type === t);

export const getItem = (id: string) => MARKET_ITEMS.find((i) => i.id === id);
